volumes:
  sngf_api_local_postgres_data: {}
  sngf_api_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sngf_api_local_django
    container_name: sngf_api_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sngf_api_production_postgres
    container_name: sngf_api_local_postgres
    volumes:
      - sngf_api_local_postgres_data:/var/lib/postgresql/data
      - sngf_api_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: sngf_api_local_mailpit
    ports:
      - "8025:8025"
