# Generated by Django 5.0.13 on 2025-04-15 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='blogs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=10)),
                ('file', models.ForeignKey(blank=True, help_text="Fichier téléchargeable de l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='files.filemodel')),
            ],
        ),
    ]
