# Generated by Django 5.0.13 on 2025-04-13 11:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ForeignKey(blank=True, help_text="Fichier téléchargeable de l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='files.filemodel'),
        ),
        migrations.AddField(
            model_name='blog',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
