# Generated by Django 5.0.13 on 2025-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
