# Generated by Django 5.0.13 on 2025-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, help_text="NB: N'ajoutez en aucun cas des émojies"),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.TextField(help_text="NB: N'ajoutez en aucun cas des émojies", max_length=250),
        ),
    ]
