# Generated by Django 5.0.13 on 2025-04-23 10:30

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_number_order_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('ea2aa073-ac64-4842-8e1d-315b4fff06ac')),
        ),
    ]
