# Generated by Django 5.0.13 on 2025-05-01 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_contact_email_alter_order_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('2246f67d-941f-4cf5-a781-db4348b444ee')),
        ),
    ]
