# Generated by Django 5.0.13 on 2025-05-11 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('65292283-81df-4877-a718-a25b8d90a9a5')),
        ),
    ]
