# Generated by Django 5.0.13 on 2025-05-11 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('4e349a62-148c-486a-befb-efc09fde8131')),
        ),
    ]
