# Generated by Django 5.0.13 on 2025-05-11 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('fe4d1636-d1ee-47ca-a30f-ac7d774fcc9d')),
        ),
    ]
