# Generated by Django 5.0.13 on 2025-05-20 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('701b8ebc-3d07-462a-9697-387d64364a81')),
        ),
    ]
