# Generated by Django 5.0.13 on 2025-06-10 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('480bc8ea-7d9d-46e5-be04-250e1779485d')),
        ),
    ]
