# Generated by Django 5.0.13 on 2025-07-05 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('db9e0722-1139-4d95-a21f-e7c9bd73dc53')),
        ),
    ]
