# Generated by Django 5.0.13 on 2025-05-20 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('54f317ef-1f03-45ef-b01a-58d60545683b')),
        ),
    ]
