# Generated by Django 5.0.13 on 2025-05-21 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('81013506-2525-435b-ab0b-653e14ece222')),
        ),
    ]
