# Generated by Django 5.0.13 on 2025-05-21 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('ee9edb80-26b6-4983-87b0-feff7b0b15e6')),
        ),
    ]
