# Generated by Django 5.0.13 on 2025-04-15 15:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du produit de base. Il est généré automatiquement et ne peut pas être modifié.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Le nom du produit.', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('AGROFORESTIERES', 'Agroforestières'), ('ENDEMIQUES_AUTOCHTONES', 'Endémiques autochtones'), ('EXOTIQUES_REBOISEMENT', 'Exotiques de reboisement'), ('ORNEMENTALES', 'Ornementales'), ('EMBROUSSAILLEMENTS', 'Embrousseillements')], help_text='La catégorie du produit. Vous pouvez choisir parmi les options proposées.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Une description détaillée du produit (facultatif).')),
                ('quantity', models.PositiveIntegerField(help_text='La quantité disponible de ce produit.')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], help_text="Le statut actuel du produit (par exemple, 'Disponible', 'Indisponible').", max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique de la graine.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Le nom des graines.', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('AGROFORESTIERES', 'Agroforestières'), ('ENDEMIQUES_AUTOCHTONES', 'Endémiques autochtones'), ('EXOTIQUES_REBOISEMENT', 'Exotiques de reboisement'), ('ORNEMENTALES', 'Ornementales'), ('EMBROUSSAILLEMENTS', 'Embrousseillements')], help_text='La catégorie des graines.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Une description détaillée des graines (facultatif).')),
                ('quantity', models.PositiveIntegerField(help_text='La quantité disponible de ces graines.')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], help_text='Le statut actuel des graines.', max_length=10)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, help_text='Le prix des graines au kilogramme.', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique de l'image de la plante. Il est généré automatiquement et ne peut pas être modifié.", primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Le fichier image de la plante. Les formats supportés sont JPG, JPEG, PNG et WEBP.', upload_to='plants/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'image, important pour l'accessibilité et le SEO.", max_length=255)),
                ('plant', models.ForeignKey(help_text='La plante à laquelle cette image est associée.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plant.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSizePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du prix par taille.', primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('PM', 'Petit modèle'), ('MM', 'Modèle moyen'), ('GM', 'Grand modèle')], help_text='La taille de la plante.', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='Le prix pour cette taille de plante.', max_digits=10)),
                ('plant', models.ForeignKey(help_text='La plante à laquelle ce prix et cette taille sont associés.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='plant.plant')),
            ],
            options={
                'unique_together': {('plant', 'size')},
            },
        ),
    ]
