# Generated by Django 5.0.13 on 2025-04-15 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('AGROFORESTIERES', 'Agroforestières'), ('ENDEMIQUES_AUTOCHTONES', 'Endémiques autochtones'), ('EXOTIQUES_REBOISEMENT', 'Exotiques de reboisement'), ('ORNEMENTALES', 'Ornementales'), ('EMBROUSSAILLEMENTS', 'Embrousseillements')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=10)),
                ('size', models.CharField(choices=[('PM', 'Petit modèle'), ('MM', 'Modèle moyen'), ('GM', 'Grand modèle')], max_length=2)),
                ('prices', models.JSONField(help_text='Exemple : {"PM": 1500.00, "MM": 2500.00, "GM": 3500.00}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('AGROFORESTIERES', 'Agroforestières'), ('ENDEMIQUES_AUTOCHTONES', 'Endémiques autochtones'), ('EXOTIQUES_REBOISEMENT', 'Exotiques de reboisement'), ('ORNEMENTALES', 'Ornementales'), ('EMBROUSSAILLEMENTS', 'Embrousseillements')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=10)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='plants/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plant.plant')),
            ],
        ),
    ]
