# Generated by Django 5.0.13 on 2025-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image_url',
        ),
    ]
