# Generated by Django 5.0.13 on 2025-04-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_remove_plant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('AGROFORESTIERES', 'AGROFORESTIERES'), ('ENDEMIQUES_AUTOCHTONES', 'ENDEMIQUES_AUTOCHTONES'), ('EXOTIQUES_REBOISEMENT', 'EXOTIQUES_REBOISEMENT'), ('ORNEMENTALES', 'ORNEMENTALES'), ('EMBROUSSAILLEMENTS', 'EMBROUSSAILLEMENTS')]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(choices=[('PM', '10-20 CM'), ('MM', '20-30 CM'), ('GM', '30-100 CM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('SEED', 'Graines'), ('PLANT', 'Plante')], max_length=10),
        ),
    ]
