# Generated by Django 5.0.13 on 2025-05-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_category_alter_plant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsizeprice',
            name='size',
            field=models.CharField(choices=[('PM', 'Petit modèle'), ('MM', 'Modèle moyen'), ('GM', 'Grand modèle'), ('EX', 'Extrème modèle'), ('UN', 'Unique modèle')], help_text='La taille de la plante.', max_length=2),
        ),
    ]
