# Generated by Django 5.0.13 on 2025-05-10 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plantsizeprice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='article_code',
            field=models.CharField(max_length=150, default='', help_text='Code de l\'article de la plante.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(max_length=100, default='', help_text='Nom scientifique de la plante.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='species_code',
            field=models.CharField(max_length=150, default='', help_text='Code de l\'espèce de la plante.'),
        ),
        migrations.AddField(
            model_name='seed',
            name='article_code',
            field=models.CharField(max_length=150, default='', help_text='Code de l\'article de la graine.'),
        ),
        migrations.AddField(
            model_name='seed',
            name='scientific_name',
            field=models.CharField(max_length=150, default='', help_text='Nom scientifique de la graine.'),
        ),
        migrations.AddField(
            model_name='seed',
            name='species_code',
            field=models.CharField(max_length=150, default='', help_text='Code de l\'espèce de la graine.'),
        ),
        migrations.AddField(
            model_name='seedimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(help_text='Le fichier image de la plante.Les formats supportés sont JPG, JPEG, PNG et WEBP.', null=True, upload_to='plants/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='seedimage',
            name='image',
            field=models.ImageField(help_text='Le fichier image de la plante.Les formats supportés sont JPG, JPEG, PNG et WEBP.', null=True, upload_to='seeds/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
