# Generated by Django 5.0.13 on 2025-05-11 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_plant_article_code_plant_scientific_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom de la catégorie : Agroforestières, Endémiques autochtones, etc.', max_length=100, unique=True)),
                ('product_type', models.CharField(choices=[('PLANT', 'Plant'), ('SEED', 'Graine')], help_text="Type de produit auquel cette catégorie s'applique (plante ou graine).", max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='poids',
            field=models.PositiveIntegerField(default=9, help_text='1 = très important, 9 = peu important'),
        ),
        migrations.AddField(
            model_name='seed',
            name='poids',
            field=models.PositiveIntegerField(default=9, help_text='1 = très important, 9 = peu important'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, help_text='La catégorie botanique associée à cette plante.', limit_choices_to={'product_type': 'PLANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant.category'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='category',
            field=models.ForeignKey(blank=True, help_text='La catégorie botanique associée à cette graine.', limit_choices_to={'product_type': 'SEED'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant.category'),
        ),
    ]
