# Generated by Django 5.0.13 on 2025-04-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_plant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='description',
            new_name='utilisation',
        ),
    ]
