# Generated by Django 5.0.13 on 2025-05-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_category_plant_poids_seed_poids_alter_plant_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
    ]
