# Generated by Django 5.0.13 on 2025-05-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_remove_category_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, help_text='La catégorie botanique associée à cette plante.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant.category'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='category',
            field=models.ForeignKey(blank=True, help_text='La catégorie botanique associée à cette graine.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant.category'),
        ),
    ]
