# Generated by Django 5.0.13 on 2025-05-11 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_alter_plant_category_alter_seed_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='category',
        ),
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Les catégories associées à cette plante.', related_name='plants', to='plant.category'),
        ),
        migrations.AddField(
            model_name='seed',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Les catégories associées à cette graine.', related_name='seeds', to='plant.category'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du produit de base.Il est généré automatiquement et ne peut pas être modifié.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seed',
            name='name',
            field=models.CharField(help_text='Le nom du produit.', max_length=100),
        ),
    ]
