# Generated by Django 5.0.13 on 2025-06-10 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_remove_plant_category_remove_seed_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nom affiché de la catégorie (par exemple, 'Agroforestières').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique de l'image de la plante.Il est généré automatiquement et ne peut pas être modifié.", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Code unique de la catégorie (par exemple, 'AGROFORESTIERES').", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='article_code',
            field=models.CharField(help_text="Code de l'article de la plante.", max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(help_text='Les catégories auxquelles cette plante appartient.', related_name='plants', to='plant.category'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(help_text='Nom scientifique de la plante.', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species_code',
            field=models.CharField(help_text="Code de l'espèce de la plante.", max_length=150),
        ),
        migrations.AlterField(
            model_name='plantsizeprice',
            name='size',
            field=models.CharField(choices=[('PM', 'Petit modèle'), ('MM', 'Modèle moyen'), ('GM', 'Grand modèle')], help_text='La taille de la plante.', max_length=2),
        ),
        migrations.AlterField(
            model_name='seed',
            name='article_code',
            field=models.CharField(help_text="Code de l'article de la graine.", max_length=150),
        ),
        migrations.AlterField(
            model_name='seed',
            name='categories',
            field=models.ManyToManyField(help_text='Les catégories auxquelles ces graines appartiennent.', related_name='seeds', to='plant.category'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique de la graine.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seed',
            name='name',
            field=models.CharField(help_text='Le nom des graines.', max_length=100),
        ),
        migrations.AlterField(
            model_name='seed',
            name='scientific_name',
            field=models.CharField(help_text='Nom scientifique de la graine.', max_length=150),
        ),
        migrations.AlterField(
            model_name='seed',
            name='species_code',
            field=models.CharField(help_text="Code de l'espèce de la graine.", max_length=150),
        ),
        migrations.AlterField(
            model_name='seedimage',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
