# Generated by Django 5.0.13 on 2025-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_alter_category_options_category_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsizeprice',
            name='size',
            field=models.CharField(choices=[('PM', 'Petit modèle'), ('MM', 'Modèle moyen'), ('GM', 'Grand modèle'), ('X', 'Extrème modèle'), ('UN', 'Unique modèle')], help_text='La taille de la plante.', max_length=2),
        ),
    ]
