name: Trigger Frontend Client Generation

on:
  push:
    branches:
      - docs/api  # la branche appropriée contenant la spécification API

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Frontend Client Generation
        run: |
          curl -X POST https://api.github.com/repos/SNGF-official/WEB/dispatches \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -d '{"event_type": "generate-client"}'
